// Tier 2 - Common Knowledge Semantic Categories (Default off)

export const tier2Categories = {
// TIER 2 - COMMON KNOWLEDGE (Default off): Everyday knowledge
  animals: [
    // Related pairs (100)
    ["dog","puppy"],["cat","kitten"],["cow","calf"],["horse","foal"],["pig","piglet"],
    ["sheep","lamb"],["goat","kid"],["chicken","chick"],["duck","duckling"],["goose","gosling"],
    ["lion","cub"],["tiger","cub"],["bear","cub"],["wolf","pup"],["fox","kit"],
    ["elephant","calf"],["giraffe","calf"],["zebra","foal"],["deer","fawn"],["rabbit","kit"],
    ["squirrel","pup"],["mouse","pup"],["rat","pup"],["hamster","pup"],["guinea pig","pup"],
    ["bird","chick"],["eagle","eaglet"],["owl","owlet"],["parrot","chick"],["penguin","chick"],
    ["fish","fry"],["shark","pup"],["whale","calf"],["dolphin","calf"],["seal","pup"],
    ["frog","tadpole"],["toad","tadpole"],["snake","snakelet"],["lizard","hatchling"],["turtle","hatchling"],
    ["butterfly","caterpillar"],["bee","larva"],["ant","larva"],["spider","spiderling"],["fly","maggot"],
    ["dog","bark"],["cat","meow"],["cow","moo"],["horse","neigh"],["pig","oink"],
    ["sheep","baa"],["goat","bleat"],["chicken","cluck"],["duck","quack"],["goose","honk"],
    ["lion","roar"],["tiger","growl"],["bear","growl"],["wolf","howl"],["fox","bark"],
    ["elephant","trumpet"],["giraffe","hum"],["zebra","bray"],["deer","bellow"],["rabbit","squeak"],
    ["squirrel","chatter"],["mouse","squeak"],["rat","squeak"],["hamster","squeak"],["guinea pig","squeak"],
    ["bird","chirp"],["eagle","screech"],["owl","hoot"],["parrot","squawk"],["penguin","honk"],
    ["fish","bubble"],["shark","silence"],["whale","song"],["dolphin","click"],["seal","bark"],
    ["frog","ribbit"],["toad","croak"],["snake","hiss"],["lizard","chirp"],["turtle","grunt"],
    ["butterfly","silence"],["bee","buzz"],["ant","silence"],["spider","silence"],["fly","buzz"],
    ["dog","bone"],["cat","fish"],["cow","grass"],["horse","hay"],["pig","corn"],
    ["sheep","grass"],["goat","grass"],["chicken","seed"],["duck","bread"],["goose","grass"],
    ["lion","meat"],["tiger","meat"],["bear","fish"],["wolf","meat"],["fox","chicken"],
    ["elephant","leaves"],["giraffe","leaves"],["zebra","grass"],["deer","grass"],["rabbit","carrot"],
    ["squirrel","nuts"],["mouse","cheese"],["rat","garbage"],["hamster","seeds"],["guinea pig","vegetables"],
    ["bird","worms"],["eagle","rabbit"],["owl","mouse"],["parrot","fruit"],["penguin","fish"],
    ["fish","plankton"],["shark","fish"],["whale","krill"],["dolphin","fish"],["seal","fish"],
    ["frog","flies"],["toad","insects"],["snake","mouse"],["lizard","insects"],["turtle","plants"],
    ["butterfly","nectar"],["bee","pollen"],["ant","sugar"],["spider","flies"],["fly","decay"],
    // Unrelated pairs (100)
    ["dog","color"],["cat","shape"],["cow","texture"],["horse","weight"],["pig","height"],
    ["sheep","color"],["goat","shape"],["chicken","texture"],["duck","weight"],["goose","height"],
    ["lion","color"],["tiger","shape"],["bear","texture"],["wolf","weight"],["fox","height"],
    ["elephant","color"],["giraffe","shape"],["zebra","texture"],["deer","weight"],["rabbit","height"],
    ["squirrel","color"],["mouse","shape"],["rat","texture"],["hamster","weight"],["guinea pig","height"],
    ["bird","color"],["eagle","shape"],["owl","texture"],["parrot","weight"],["penguin","height"],
    ["fish","color"],["shark","shape"],["whale","texture"],["dolphin","weight"],["seal","height"],
    ["frog","color"],["toad","shape"],["snake","texture"],["lizard","weight"],["turtle","height"],
    ["butterfly","color"],["bee","shape"],["ant","texture"],["spider","weight"],["fly","height"],
    ["dog","color"],["cat","shape"],["cow","texture"],["horse","weight"],["pig","height"],
    ["sheep","color"],["goat","shape"],["chicken","texture"],["duck","weight"],["goose","height"],
    ["lion","color"],["tiger","shape"],["bear","texture"],["wolf","weight"],["fox","height"],
    ["elephant","color"],["giraffe","shape"],["zebra","texture"],["deer","weight"],["rabbit","height"],
    ["squirrel","color"],["mouse","shape"],["rat","texture"],["hamster","weight"],["guinea pig","height"],
    ["bird","color"],["eagle","shape"],["owl","texture"],["parrot","weight"],["penguin","height"],
    ["fish","color"],["shark","shape"],["whale","texture"],["dolphin","weight"],["seal","height"],
    ["frog","color"],["toad","shape"],["snake","texture"],["lizard","weight"],["turtle","height"],
    ["butterfly","color"],["bee","shape"],["ant","texture"],["spider","weight"],["fly","height"],
    ["dog","color"],["cat","shape"],["cow","texture"],["horse","weight"],["pig","height"],
    ["sheep","color"],["goat","shape"],["chicken","texture"],["duck","weight"],["goose","height"],
    ["lion","color"],["tiger","shape"],["bear","texture"],["wolf","weight"],["fox","height"],
    ["elephant","color"],["giraffe","shape"],["zebra","texture"],["deer","weight"],["rabbit","height"],
    ["squirrel","color"],["mouse","shape"],["rat","texture"],["hamster","weight"],["guinea pig","height"],
    ["bird","color"],["eagle","shape"],["owl","texture"],["parrot","weight"],["penguin","height"],
    ["fish","color"],["shark","shape"],["whale","texture"],["dolphin","weight"],["seal","height"],
    ["frog","color"],["toad","shape"],["snake","texture"],["lizard","weight"],["turtle","height"],
    ["butterfly","color"],["bee","shape"],["ant","texture"],["spider","weight"],["fly","height"]
  ],

  // NEW: Advanced Semantic Categories (Research-Aligned)
  semanticComplexity: [
    // Related pairs - Abstract semantic relationships (50)
    ["justice","fairness"],["wisdom","knowledge"],["courage","bravery"],["honor","respect"],["integrity","honesty"],
    ["compassion","empathy"],["patience","tolerance"],["humility","modesty"],["gratitude","appreciation"],["forgiveness","mercy"],
    ["loyalty","faithfulness"],["trust","confidence"],["hope","optimism"],["peace","harmony"],["freedom","liberty"],
    ["equality","fairness"],["democracy","freedom"],["education","learning"],["health","wellness"],["beauty","aesthetics"],
    ["creativity","innovation"],["tradition","custom"],["culture","heritage"],["language","communication"],["art","expression"],
    ["music","harmony"],["poetry","rhythm"],["dance","movement"],["theater","performance"],["literature","writing"],
    ["philosophy","wisdom"],["science","knowledge"],["mathematics","logic"],["history","past"],["future","tomorrow"],
    ["technology","innovation"],["progress","advancement"],["development","growth"],["evolution","change"],["revolution","transformation"],
    ["discovery","finding"],["invention","creation"],["exploration","journey"],["adventure","excitement"],["challenge","difficulty"],
    ["success","achievement"],["failure","mistake"],["victory","triumph"],["defeat","loss"],["strength","power"],
    // Unrelated pairs - No clear abstract relationship (50)
    ["justice","color"],["fairness","shape"],["courage","texture"],["bravery","weight"],["honor","height"],
    ["respect","color"],["integrity","shape"],["honesty","texture"],["compassion","weight"],["empathy","height"],
    ["patience","color"],["tolerance","shape"],["humility","texture"],["modesty","weight"],["gratitude","height"],
    ["appreciation","color"],["forgiveness","shape"],["mercy","texture"],["loyalty","weight"],["faithfulness","height"],
    ["trust","color"],["confidence","shape"],["hope","texture"],["optimism","weight"],["peace","height"],
    ["harmony","color"],["freedom","shape"],["liberty","texture"],["equality","weight"],["democracy","height"],
    ["education","color"],["learning","shape"],["health","texture"],["wellness","weight"],["beauty","height"],
    ["aesthetics","color"],["creativity","shape"],["innovation","texture"],["tradition","weight"],["custom","height"],
    ["culture","color"],["heritage","shape"],["language","texture"],["communication","weight"],["art","height"],
    ["expression","color"],["music","shape"],["poetry","texture"],["rhythm","weight"],["dance","height"],
    ["movement","color"],["theater","shape"],["performance","texture"],["literature","weight"],["writing","height"],
    ["philosophy","color"],["science","shape"],["knowledge","texture"],["mathematics","weight"],["logic","height"],
    ["history","color"],["past","shape"],["future","texture"],["tomorrow","weight"],["technology","height"],
    ["progress","color"],["advancement","shape"],["development","texture"],["growth","weight"],["evolution","height"],
    ["change","color"],["revolution","shape"],["transformation","texture"],["discovery","weight"],["finding","height"],
    ["invention","color"],["creation","shape"],["exploration","texture"],["journey","weight"],["adventure","height"],
    ["excitement","color"],["challenge","shape"],["difficulty","texture"],["success","weight"],["achievement","height"],
    ["failure","color"],["mistake","shape"],["victory","texture"],["triumph","weight"],["defeat","height"],
    ["loss","color"],["strength","shape"],["power","texture"],["justice","weight"],["fairness","height"]
  ],

  cognitiveLoad: [
    // Related pairs - High cognitive load semantic decisions (50)
    ["metaphor","analogy"],["symbol","representation"],["concept","idea"],["principle","rule"],["theory","hypothesis"],
    ["evidence","proof"],["analysis","examination"],["synthesis","combination"],["evaluation","assessment"],["interpretation","explanation"],
    ["inference","conclusion"],["deduction","reasoning"],["induction","generalization"],["abstraction","simplification"],["concretization","specification"],
    ["categorization","classification"],["comparison","contrast"],["similarity","difference"],["pattern","structure"],["system","organization"],
    ["framework","model"],["paradigm","approach"],["methodology","technique"],["strategy","tactic"],["procedure","process"],
    ["mechanism","function"],["process","operation"],["activity","action"],["behavior","conduct"],["performance","execution"],
    ["outcome","result"],["consequence","effect"],["cause","reason"],["purpose","goal"],["objective","target"],
    ["intention","plan"],["design","blueprint"],["structure","framework"],["organization","arrangement"],["system","network"],
    ["relationship","connection"],["association","link"],["correlation","relationship"],["dependency","reliance"],["interaction","exchange"],
    // Unrelated pairs - No clear cognitive relationship (50)
    ["metaphor","color"],["analogy","shape"],["concept","texture"],["idea","weight"],["principle","height"],
    ["rule","color"],["theory","shape"],["hypothesis","texture"],["evidence","weight"],["proof","height"],
    ["analysis","color"],["examination","shape"],["synthesis","texture"],["combination","weight"],["evaluation","height"],
    ["assessment","color"],["interpretation","shape"],["explanation","texture"],["inference","weight"],["conclusion","height"],
    ["deduction","color"],["reasoning","shape"],["induction","texture"],["generalization","weight"],["abstraction","height"],
    ["simplification","color"],["concretization","shape"],["specification","texture"],["categorization","weight"],["classification","height"],
    ["comparison","color"],["contrast","shape"],["similarity","texture"],["difference","weight"],["pattern","height"],
    ["structure","color"],["system","shape"],["organization","texture"],["framework","weight"],["model","height"],
    ["paradigm","color"],["approach","shape"],["methodology","texture"],["technique","weight"],["strategy","height"],
    ["tactic","color"],["procedure","shape"],["process","texture"],["mechanism","weight"],["function","height"],
    ["operation","color"],["activity","shape"],["action","texture"],["behavior","weight"],["conduct","height"],
    ["performance","color"],["execution","shape"],["outcome","texture"],["result","weight"],["consequence","height"],
    ["effect","color"],["cause","shape"],["reason","texture"],["purpose","weight"],["goal","height"],
    ["objective","color"],["target","shape"],["intention","texture"],["plan","weight"],["design","height"],
    ["blueprint","color"],["structure","shape"],["framework","texture"],["organization","weight"],["arrangement","height"],
    ["system","color"],["network","shape"],["relationship","texture"],["connection","weight"],["association","height"],
    ["link","color"],["correlation","shape"],["relationship","texture"],["dependency","weight"],["reliance","height"],
    ["interaction","color"],["exchange","shape"],["metaphor","texture"],["analogy","weight"],["concept","height"]
  ],
};
